# Generated by Django 3.2 on 2021-05-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Todo',
        ),
    ]
